# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('START', 'Start'), ('END', 'End')], max_length=10, verbose_name='Type')),
                ('date_register', models.DateTimeField(verbose_name='Time register')),
                ('call_id', models.CharField(max_length=5, verbose_name='Call')),
                ('source', models.CharField(max_length=12, verbose_name='Origin phone number')),
                ('destination', models.CharField(max_length=12, verbose_name='Destination phone number')),
            ],
        ),
    ]
